<?php

namespace LyliBundle\Repository;

/**
 * OpendataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpendataRepository extends \Doctrine\ORM\EntityRepository
{
}
